# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 1, 43, 56, 651775, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
