# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171026_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О файле')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/documents', verbose_name='Выберите документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Докуенты',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 2, 26, 52, 511519, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
